### ISSUE TITLE
Please add button to 'Background Jobs' for remove stuck job

### ISSUE THREAD

**Issue by wuhgit** [huginn/huginn#2673]
> If you stopped the docker images the Job is only stuck in the database. The only way to remove it is to manually delete the database row.
> 
> ```
> # get a shell inside the docker container (replace huginn with the name or id of the container)
> docker exec -it huginn /bin/bash
> 
> # source the environment file
> source .env
> 
> # get a rails console
> bundle exec rails console
> 
> # inside the rails console delete  the job 
> Delayed::Job.where('locked_at IS NOT NULL AND locked_by IS NOT NULL AND failed_at IS NULL').destroy_all
> 
> _Originally posted by @dsander in https://github.com/huginn/huginn/issues/1988#issuecomment-548334831_

@dsander

After a few months of stable running, this problem appeared again this morning, hundreds of jobs were stuck, I tried your method and it was really useful!

There are already three buttons in the 'Background Jobs' page, Can you add another button to execute this command? In this case, when users encounter similar situations, they do not have to log in to the VPS every time to execute the code.

Thanks!

**Comment by dsander** [comment]
Adding the button should not be much work, but I am not sure in which cases it would help. The jobs should only get stuck when the background processor failed for some reason. 

Didn't you also need to restart the docker container to unstuck the process?

**Comment by wuhgit** [comment]
> 
> 
> Adding the button should not be much work, but I am not sure in which cases it would help. The jobs should only get stuck when the background processor failed for some reason.
> 
> Didn't you also need to restart the docker container to unstuck the process?

Not need to restart docker at least this time.
When I found out, that job was stuck for about seven or eight hours, with dozens of pages of queued jobs following up.
Using the buttons on the page can not remove this stuck job, I click 'Remove all jobs' to remove all queued jobs first, then login into VPS to run that code, the stuck task is successfully removed.
After a while, a lot of queued tasks appeared in 'Background Jobs' again, but none of them were running, so I randomly found an Agent to perform a Dry Run, and everything was running normally.

**Comment by dsander** [comment]
That sounds odd, normally when jobs are stuck that way it was caused by the/a background processor that hangs or crashed. A `Dry Run` of an Agent is performed by the web application server, not the background processes, maybe it was a coincidence that the background process unstuck itself somehow around the same time.

(Assigning myself to the issue so that I don't forget about it, if anyone else wants to tackle the issue feel free to do so)

**Comment by wuhgit** [comment]
I think you're right, maybe it's just coincidence.
If I encounter the same problem next time, what else do I need to pay attention to so that you can continue troubleshooting?
Thank you for your help.

**Comment by dsander** [comment]
It would be interesting to see the logs if the background process really continues to work without a restart after you delete the stuck jobs from the database.

**Comment by wuhgit** [comment]
It's weird.
This morning, the background job is stuck more than four hours again. and hundreds of jobs queued, I am going to start logging, but I don’t know how to do it, so I search in the issues and enter into docker.
When I executing the command `sudo bundle exec rake production:status`, the docker system prompts that `runit` needs to be installed, then I performed apt installation.
But at this moment, all of the jobs started to work normally again, which means that the commands and operations may not solve the problem before, but because of the docker itself?
BTW, I still don't know how to output logs from docker, can you please tell me how to do it? 
Thanks!

**Comment by wuhgit** [comment]
My previous operation may be stupid, the next jobs appeared error ```Broken pipe @ io_writev-<STDOUT> /app/app/models/agent_log.rb:16:in `write'```, I don’t know how to solve it So I deleted the container and reinstalled it.

**Comment by dsander** [comment]
You can get the logs from outside of the container with `docker logs <name of the container>`, there are a couple of options to tail the logs and limit the output, `docker logs` should give you a help page.

Is it possible that the jobs are not really stuck, but only take a long time to finish?

**Comment by wuhgit** [comment]
These stuck jobs are very common Website Agent, it may take up to tens of seconds to complete the execution generally, I think it seems unlikely that it will take several hours to complete the task.

Now that I know how to export the log, if I encounter this again next time, I will try to provide the log for your analysis here.

Thank you very much!

**Comment by guanzo** [comment]
All of my background jobs always hang after my PC wakes up. Running huginn with Docker on Windows 10. Would love to hear a solution so I don't have to run `docker restart huginn` every day.

**Comment by dsander** [comment]
@guanzo In general Huginn is designed to run on a server that is online 24/7. It is possible that if we add support for the background jobs to re-establish the database connection (if it's possible) it will also improve your use case, but I doubt that the experience will be perfect.

**Comment by wuhgit** [comment]
@dsander 

Finally waited for another job to be stuck 😅
In the ‘background jobs’ page, this job was stuck for about an hour, so I went to the background and output the logs for the last two hours.

Because a lot of content is the webpage output by the agent, causing the log file capacity to be too large, I replaced all of this content with a brief code, such as <agent_name>, <parsed_result>, etc. I hope it will not confuse your analysis.

[huginn_20200208.log](https://github.com/huginn/huginn/files/4173730/huginn_20200208.log)

**Comment by dsander** [comment]
Hmm I can't find anything in the log that would explain a stuck job. Which Agent (the name and id) got stuck? Do you have the background processor logs files? `/home/huginn/huginn/log/*/current`

**Comment by wuhgit** [comment]
@dsander

I don't have such a log file here, either on the host or inside docker.
I remember the stuck agent is `Agent#226` 
Is this possible? If a job gets stuck, the docker log file is no longer updated?

What else needs attention? I will provide other logs that may be helpful next time a similar problem occurs

**Comment by dsander** [comment]
Ah, got it I forgot you are running in Docker. You you running just one container or multiple? 

If you are running multiple containers can you grab all logs next time something goes wrong?

>  Is this possible? If a job gets stuck, the docker log file is no longer updated?

It depends, if you are just running the `huginn/huginn` image in one container the most common case of a stuck job is a WebsiteAgent that runs longer than `DELAYED_JOB_MAX_RUNTIME`. In some cases the background processes get stuck completely, sometimes it's just the job processing, sometimes everything keeps working as expected.

**Comment by wuhgit** [comment]
@dsander

I have only one docker container, which is huginn/huginn.

The stuck jobs are all WebsiteAgent these times, is there any solution to this? such as automatically kill a job after a certain time?

I noticed that you mentioned `DELAYED_JOB_MAX_RUNTIME` and I found that I may have missed something in the previous description.
when I deployed the container, I have set `DELAYED_JOB_MAX_RUNTIME` during deployment, I used the following extra command:

```
...
-e DATABASE_POOL=60 \
-e SCHEDULER_FREQUENCY=3 \
-e DELAYED_JOB_SLEEP_DELAY=20 \
-e DELAYED_JOB_MAX_RUNTIME=10 \
...
```

These commands were determined after repeated testing. The default deployment often caused the VPS CPU usage to be too high. the VPS I use is 1 core CPU / 1G RAM (and 1.5G swap on SSD)
I think this configuration is not enough to run huginn smoothly, but compared to the previous manual deployment, the stability and reliability of running with docker has been very good.

**Comment by dsander** [comment]
> The stuck jobs are all WebsiteAgent these times, is there any solution to this? such as automatically kill a job after a certain time?

Sadly nothing at the moment, I have a few ideas on how to reduce the amount of stuck jobs or fix it completely, but I need to find time to work on that.



> I have set `DELAYED_JOB_MAX_RUNTIME` during deployment, I used the following extra command:

The values look OK to me, if you are crawling websites that take a really long time to respond (over 10 minutes), jobs could still get stuck. But fixing that is really something we have to do.

**Comment by wuhgit** [comment]
It sounds like it will take some time, I will close this issue now, waiting for your good news, hope that some day in the future, this issue can be completely resolved.
Thank you again for your efforts 👍

**Comment by virtadpt** [comment]
> Adding the button should not be much work, but I am not sure in which cases it would help. The jobs should
> only get stuck when the background processor failed for some reason.

I run into this once or twice a month, usually with IPv6 related services.  Such a button would /really/ help.
