### ISSUE TITLE
PostAgent - weird json utf8 error

### ISSUE THREAD

**Issue by oltdaniel** [huginn/huginn#2774]
## Setup

Using an PostAgent to submit to a login form. No redirection on the server, simple form structure with form content type. Config:

```json
{
  "post_url": "https://---",
  "expected_receive_period_in_days": "1",
  "content_type": "form",
  "method": "post",
  "payload": {
    "id":"---",
    "passwd":"---",
    "Action":"---"
  },
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "clean"
}
```

## Error

```
[00:00:00] ERROR -- : Exception during dry-run. source sequence is illegal/malformed utf-8: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:38:in `to_json'
...
/usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
```

Full error [here](https://pastebin.com/raw/LDVF6xKv).

## Question

Is this an error in the response or request? The target site is pretty old and uses headers with:
```html
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
                      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head><link href="favicon.ico" rel="shortcut icon" />
    <meta content="text/html; charset=ISO-8859-1" http-equiv="Content-Type" />
<!-- .... ->
```

**Comment by dsander** [comment]
In my experience errors like these are mostly caused by websites reporting a wrong encoding. Huginn does not try to guess the encoding of the data it receives, but trusts the encoding set by the HTTP response.

**Comment by lessrand** [comment]
Hello,

the problem is - we cannot change encoding from external websites - so it would be very useful, to set/change encoding. 

kind regards

Randy

**Comment by oltdaniel** [comment]
Thats true what @lessrand said. I tried different HTTP headers to froce the server to send an different encoding but no success. There **was** also an HTTP Header to set an accepted charset for the client to the server, however it support hast been dropped and hasn't been implemented at all, as the Clients tend to do more work on their own the the responses as seen in the last years.

So any possible way, to add this to the Huginn project by default?

**Comment by dsander** [comment]
In cases like these the headers send by the client rarely make a difference. I am guessing that the server is "thinking" the content is encoded in - for example - `utf8`, thus sending it as the encoding, but the actual HTML is written in a different encoding.

The `Website-` and `PostAgent` support the `force_encoding` configuration option. It can be used to force Huginn to use a different encoding.

**Comment by oltdaniel** [comment]
@dsander Tested but doesn't change anything. Still receiving the same error. And if you look into line 6 of the error message (`/app/lib/json_with_indifferent_access.rb:10:in `dump'`) you can see that it is actually about constructing an JSON Object for the function `build_event` from `agents.rb`. I'm not an Huginn expert, which means I don't know the exact structure. But `force_encoding` changes nothing for me at this point.

**Comment by dsander** [comment]
How did you determine the actual encoding of the data returned by the website? Can you share the URL or the raw data?

**Comment by oltdaniel** [comment]
@dsander See attachment.
```
$ curl URL >> out.html
$ file -i out.html
out.html: text/xml; charset=iso-8859-1
```

#### Attachments
[out.html.zip](https://github.com/huginn/huginn/files/4608077/out.html.zip)

###### **NOTE**: needed to send .zip as GitHub blacklisted .html

**Comment by dsander** [comment]
Hmm yes the [charlock_holmes gem](https://github.com/brianmario/charlock_holmes) also thinks it's `ISO-8859-1`, you did try to set `force_encoding` to `ISO-8859-1` as a "root" configuration option of the `PostAgent`?

**Comment by oltdaniel** [comment]
@dsander Yes that worked. I will see how this encoding will flow through the following agents, and report back later.

**Comment by oltdaniel** [comment]
@dsander Issue has been solved by this setting. Messages created by this Agent do not cause any issues in receiver agents.

**Comment by lessrand** [comment]
Just one more comment on this.

The same issue is true for CSVReader,SMTPAgent a.s.o.
If you are not in an english speaking country you always have to handle various encodings and I cannot force my mail provider or my data source to switch from Latin1 or Eastern European Encoding to UTF8. Yes in a perfect world there would be utf8 in every system, but reality is not like that you have ansi, latin...

So please make the agents aware of that and allow a encoding parameter for the sources that automatically converts from whatever encoding to utf8 and huginn agents will be way more useful.

kind regards 

Randy

**Comment by dsander** [comment]
@lessrand Hmm the `CsvAgent` only accepts data that is already in Huginn, so the encoding should not be an issue because we store everything as UTF-8. I don't know to which Agent to are referring to as `SMTPAgent`.

**Comment by lessrand** [comment]
Dear dsander,

CSVReader reads a file I get by ftp - so if I want to convert that ftp file to utf8 i need some conversion.
It may be that it is ansi, latin1 or something else. maybe an encoding cnversion agent might be an alternative.

SMTPAgent fails when the mail server returns non utf8 characters, because it is set to some other encoding.
A handling of mail Input that is not utf8 encoded would be very useful.

kind regards 

Randy

**Comment by dsander** [comment]
Gotcha, what I am saying is that if we add (forced) encoding conversion it has to be done at the "edge", i.e. the Agent that first imports the data into Huginn. I just looked at the code and the `FtpsiteAgent` already supports `force_encoding` (it's even documented in the Agent description which isn't always the case 😉 ). I still don't know what the `SMTPAgent` is though.
